---
- name: checkout dotfiles from github
  git: repo=git@github.com:kurisankaku/dotfiles.git
       accept_hostkey=yes
       dest=~/dotfiles

- name: create symbolic link to _vimrc
  file: src=~/dotfiles/_vimrc dest=~/.vimrc state=link

- name: create autoload directory
  file: path=~/.vim/autoload state=directory

- name: download plug.vim file
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim
